# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import easy_thumbnails.fields
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', notes.models.UpperCaseCharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HttpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('remote_addr', models.CharField(db_index=True, max_length=39)),
                ('req_method', models.CharField(max_length=16)),
                ('req_protocol', models.CharField(max_length=16)),
                ('req_path', models.TextField()),
                ('req_headers_json', models.TextField()),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=3036)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/notes')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Upper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', notes.models.UpperCaseCharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='notes',
            field=models.ManyToManyField(to='notes.Notes'),
        ),
    ]
